apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rancher-role-binding
subjects:
- kind: ServiceAccount
  name: rancher
  namespace: rancher
roleRef:
  kind: ClusterRole
  name: rancher-role
  apiGroup: rbac.authorization.k8s.io
