# rancher-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: rancher
  namespace: rancher
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rancher
  template:
    metadata:
      labels:
        app: rancher
    spec:
      containers:
      - name: rancher
        image: rancher/rancher:v2.7.0
        ports:
        - containerPort: 80
        - containerPort: 443
        args:
        - --http-listen-port=80
        - --https-listen-port=443
