apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdsm
  labels:
    app: vdsm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vdsm
  template:
    metadata:
      labels:
        app: vdsm
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
      - name: vdsm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - name: vdsm-storage
          mountPath: /mnt/user/Talos
        - name: tmp
          mountPath: /tmp
        - name: var-tmp
          mountPath: /var/tmp
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
      - name: vdsm-storage
        persistentVolumeClaim:
          claimName: vdsm-pvc
      - name: tmp
        emptyDir: {}
      - name: var-tmp
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
