apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdsm
  labels:
    app: vdsm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vdsm
  template:
    metadata:
      labels:
        app: vdsm
    spec:
      {{- if .Values.serviceAccount.create }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- end }}
      initContainers:
      - name: init-permissions
        image: busybox:1.35
        command: ['sh', '-c']
        args:
        - |
          mkdir -p /var/lib/nginx/body /var/lib/nginx/fastcgi /var/lib/nginx/proxy /var/lib/nginx/scgi /var/lib/nginx/uwsgi /var/log/nginx /var/cache/nginx
          chown -R 33:33 /var/lib/nginx /var/log/nginx /var/cache/nginx
          chmod -R 755 /var/lib/nginx /var/log/nginx /var/cache/nginx
        volumeMounts:
        - name: tmp
          mountPath: /tmp
        - name: var-tmp
          mountPath: /var/tmp
        securityContext:
          runAsUser: 0
          runAsGroup: 0
      containers:
      - name: vdsm
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: 8080
        securityContext:
          {{- toYaml .Values.securityContext | nindent 10 }}
        volumeMounts:
        - name: vdsm-storage
          mountPath: /mnt/user/Talos
        - name: tmp
          mountPath: /tmp
        - name: var-tmp
          mountPath: /var/tmp
        resources:
          {{- toYaml .Values.resources | nindent 8 }}
      volumes:
      - name: vdsm-storage
        persistentVolumeClaim:
          claimName: vdsm-pvc
      - name: tmp
        emptyDir: {}
      - name: var-tmp
        emptyDir: {}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
