apiVersion: apps/v1
kind: Deployment
metadata:
  name: vdsm
  labels:
    app: vdsm
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vdsm
  template:
    metadata:
      labels:
        app: vdsm
    spec:
      containers:
      - name: vdsm
<<<<<<< HEAD
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
=======
        image: your-vdsm-image:latest
>>>>>>> parent of f645c85 (Update deployment.yaml)
        ports:
        - containerPort: 8080
        securityContext:
          privileged: true
          capabilities:
            add:
            - NET_ADMIN
            - SYS_ADMIN
            - SYS_RAWIO
        volumeMounts:
        - name: vdsm-storage
          mountPath: /mnt/user/Talos
        - name: kvm-device
          mountPath: /dev/kvm
        - name: dev-tty
          mountPath: /dev/tty
        - name: dev-urandom
          mountPath: /dev/urandom
        - name: proc
          mountPath: /proc
        - name: sys
          mountPath: /sys
        resources:
          {{- toYaml .Values.resources | nindent 12 }}
      volumes:
<<<<<<< HEAD
      - name: vdsm-storage
        persistentVolumeClaim:
          claimName: vdsm-pvc
      - name: kvm-device
        hostPath:
          path: /dev/kvm
          type: CharDevice
      - name: dev-tty
        hostPath:
          path: /dev/tty
          type: CharDevice
      - name: dev-urandom
        hostPath:
          path: /dev/urandom
          type: CharDevice
      - name: proc
        hostPath:
          path: /proc
          type: Directory
      - name: sys
        hostPath:
          path: /sys
          type: Directory
=======
      - name: nfs-storage
        nfs:
          server: 10.1.1.2
          path: /mnt/user/Talos
>>>>>>> parent of f645c85 (Update deployment.yaml)
