apiVersion: v1
kind: PersistentVolume
metadata:
  name: vdsm-pv
  labels:
    app: vdsm
spec:
  capacity:
    storage: {{ .Values.storage.resources.requests.storage }}
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ .Values.storage.storageClassName }}
  nfs:
    server: {{ .Values.storage.nfs.server }}
    path: {{ .Values.storage.nfs.path }}
