apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdsm-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{ .Values.storage.resources.requests.storage }}
  storageClassName: nfs
  volumeMode: Filesystem