apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdsm-pvc
  labels:
    app: vdsm
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  resources:
    requests:
      storage: {{ .Values.storage.resources.requests.storage }}
  storageClassName: {{ .Values.storage.storageClassName }}
  volumeMode: Filesystem