apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vdsm-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: nfs
  volumeMode: Filesystem
  selector:
    matchLabels:
      app: vdsm