apiVersion: v1
kind: Service
metadata:
  name: vdsm-service
  labels:
    app: vdsm
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    app: vdsm