apiVersion: v1
kind: Service
metadata:
  name: {{ include "vdsm.fullname" . }}
  labels:
    {{- include "vdsm.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vdsm.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "vdsm.fullname" . }}-headless
  labels:
    {{- include "vdsm.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "vdsm.selectorLabels" . | nindent 4 }}
