apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ark-ascended
  namespace: argocd
spec:
  destination:
    namespace: games
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://jsknnr.github.io/helm-charts
    chart: ark-survival-ascended
    targetRevision: latest
    helm:
      valueFiles:
        - myvalues.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
