apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ark-ascended
  namespace: argocd
spec:
  project: default
  destination:
    namespace: games
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/Valraevn/argocd.git
    targetRevision: master
    path: Ark-ascended-server
    helm:
      releaseName: ark-ascended
      chart: ark-survival-ascended
      repo: https://jsknnr.github.io/helm-charts
      valueFiles:
        - values.yaml
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
