apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vdsm
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
    argocd.argoproj.io/sync-options: "PrunePropagationPolicy=foreground"
    argocd.argoproj.io/description: "vDSM deployment with local host storage from /var/vdsm"
spec:
  project: default
  source:
    repoURL: https://github.com/your-username/your-repo
    targetRevision: HEAD
    path: ArgoCD/vDSM_helm
    helm:
      values: |
        storage:
          type: "hostPath"
          hostPath: "/var/vdsm"
        replicaCount: 3
  destination:
    server: https://kubernetes.default.svc
    namespace: storage
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
