storage:
  nfs:
    server: "10.1.1.2"
    path: "/mnt/user/Talos"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "16Gi"

replicaCount: 1

image:
  repository: "vdsm/virtual-dsm"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 80

# Security context for vDSM container
securityContext:
  privileged: true
  capabilities:
    add:
    - NET_ADMIN
    - SYS_ADMIN
    - SYS_RAWIO

# Resource limits and requests
resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "8Gi"
    cpu: "4000m"
  
nodeSelector: {}

tolerations: []

affinity: {}
