storage:
  nfs:
    server: "10.1.1.2"
    path: "/mnt/user/Talos"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "16Gi"
  storageClassName: "nfs"

replicaCount: 1

image:
  repository: "vdsm/virtual-dsm"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: "vdsm-serviceaccount"

# Security context for vDSM container - baseline compliant but allows root and file operations
securityContext:
  # No privileged mode for baseline compliance
  privileged: false
  # Add minimal capabilities needed for nginx and file operations
  capabilities:
    add:
    - CHOWN
    - SETGID
    - SETUID
    drop:
    - ALL
  # Allow root user since vDSM requires root privileges
  runAsNonRoot: false
  runAsUser: 0
  runAsGroup: 0
  fsGroup: 0

# Alternative security context for users who need additional capabilities
# Note: This requires a more permissive Pod Security Standard (privileged)
# Uncomment and use this instead of the above securityContext if you need:
# - NET_ADMIN for network management
# - SYS_ADMIN for system administration
# - SYS_RAWIO for raw I/O operations
#
# securityContext:
#   privileged: true
#   capabilities:
#     add:
#     - NET_ADMIN
#     - SYS_ADMIN
#     - SYS_RAWIO

# Resource limits and requests
resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "8Gi"
    cpu: "4000m"
  
nodeSelector: {}

tolerations: []

affinity: {}
