replicaCount: 3

image:
  repository: vdsm/vdsm
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: ClusterIP
  port: 8080
  targetPort: 8080

storage:
  # Local storage configuration for host path
  type: "hostPath"  # Options: "hostPath", "pvc"
  hostPath: "/var/vdsm"
  # PVC configuration (used when type is "pvc")
  storageClass: "standard"
  size: 16Gi
  volumeMode: Filesystem

resources:
  limits:
    cpu: 1000m
    memory: 1024Mi
  requests:
    cpu: 250m
    memory: 256Mi

# Security configuration for Pod Security Standards compliance
security:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000
  # Set to false if you need privileged access
  allowPrivilegeEscalation: false
  # Set to true if you need to write to root filesystem
  readOnlyRootFilesystem: false

nodeSelector: {}
tolerations: []
affinity: {}

config:
  logLevel: info
  dataDir: /var/lib/vdsm

# ServiceAccount configuration
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # Automount API credentials for the Service Account
  automountServiceAccountToken: true
