storage:
  nfs:
    server: "10.1.1.2"
    path: "/mnt/user/Talos"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "16Gi"
  storageClassName: "nfs"

replicaCount: 1

image:
  repository: "vdsm/virtual-dsm"
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  enabled: true
  type: ClusterIP
  port: 8080

serviceAccount:
  create: true
  name: "vdsm-serviceaccount"

# Security context for vDSM container - adjusted for baseline compliance
securityContext:
  # Remove privileged mode for baseline compliance
  privileged: false
  # Keep only essential capabilities
  capabilities:
    add:
    - NET_ADMIN
    # Remove SYS_ADMIN and SYS_RAWIO for baseline compliance
  # Add runAsNonRoot for better security
  runAsNonRoot: true
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# Resource limits and requests
resources:
  requests:
    memory: "2Gi"
    cpu: "1000m"
  limits:
    memory: "8Gi"
    cpu: "4000m"
  
nodeSelector: {}

tolerations: []

affinity: {}
